using System;
using System.Collections.Generic;

namespace PKHeX.Core;

/// <summary>
/// <see cref="SaveFile"/> lifetime stat tracking
/// </summary>
public static class Records
{
    private const byte LargeRecordCount = 100; // int32
    private const byte SmallRecordCount = 100; // int16
    private const byte Count = LargeRecordCount + SmallRecordCount;

    /// <summary>
    /// Gets the maximum value for the specified record using the provided maximum list.
    /// </summary>
    /// <param name="recordID">Record ID to retrieve the maximum for</param>
    /// <param name="maxes">Maximum enum values for each record</param>
    /// <returns>Maximum the record can be</returns>
    public static int GetMax(int recordID, ReadOnlySpan<byte> maxes)
    {
        if ((byte)recordID >= Count)
            return 0;
        return MaxByType[maxes[recordID]];
    }

    public static int GetOffset(int baseOfs, int recordID) => recordID switch
    {
        < LargeRecordCount => baseOfs + (recordID * sizeof(int)),
        < Count => baseOfs + (LargeRecordCount * sizeof(int)) + ((recordID - LargeRecordCount) * sizeof(ushort)),
        _ => -1,
    };

    private static ReadOnlySpan<int> MaxByType => new[] {999_999_999, 9_999_999, 999_999, 99_999, 65535, 9_999, 999, 7};

    public static ReadOnlySpan<byte> DailyPairs_6 => new byte[] {29, 30, 110, 111, 112, 113, 114, 115, 116, 117};
    public static ReadOnlySpan<byte> DailyPairs_7 => new byte[] {22, 23, 110, 111, 112, 113, 114, 115, 116, 117};

    /// <summary>
    /// Festa pairs; if updating the lower index record, update the Festa Mission record if currently active?
    /// </summary>
    public static ReadOnlySpan<byte> FestaPairs_7 => new byte[]
    {
        175, 6,
        176, 33,
        177, 8,
        179, 38,
        181, 74,
        182, 73,
        183, 7,
        184, 159,
        185, 9,
    };
}

public static class RecordLists
{
    public static readonly Dictionary<int, string> RecordList_6 = new()
    {
        {000, "步数"},
        {001, "保存的次数"},
        {002, "剧情情节完成时间"},
        {003, "骑自行车次数"},
        {004, "总对战次数"},
        {005, "野生宝可梦对战"},
        {006, "训练家对战"},
        {007, "宝可梦捕获"},
        {008, "钓鱼捕获"},
        {009, "孵蛋次数"},
        {010, "宝可梦进化"},
        {011, "宝可梦在宝可梦中心治愈"},
        {012, "通讯交换"},
        {013, "通讯对战"},
        {014, "通讯对战胜利"},
        {015, "通讯对战失败"},
        {016, "WiFi交换"},
        {017, "WiFi对战"},
        {018, "WiFi对战胜利"},
        {019, "WiFi对战失败"},
        {020, "红外线交换"},
        {021, "红外线对战"},
        {022, "红外线对战胜利"},
        {023, "红外线对战失败"},
        {024, "超市大量购买"},
        {025, "花费的钱"},
        {026, "看电视的次数"},
        {027, "存放在寄放屋的宝可梦"},
        {028, "宝可梦被击败次数"},
        {029, "获得的经验值（最高）"},
        {030, "获得的经验值（当天）"},
        {031, "存放在GTS中"},
        {032, "更改精灵昵称"},
        {033, "收到的奖励高级球"},
        {034, "赢得的对战点数"},
        {035, "消耗的对战点数"},

        {037, "餐厅小费: ★☆☆"},
        {038, "餐厅小费: ★★☆"},
        {039, "餐厅小费: ★★★"},
        {040, "餐厅小费: 回转梦想家"},
        {041, "咖啡馆1小费"},
        {042, "咖啡馆2小费"},
        {043, "咖啡馆3小费"},
        {044, "摄影师小费"},
        {045, "果汁馆小费"},
        {046, "诗人小费"},
        {047, "宝可美容沙龙馆修建师小费"},
        {048, "试炼屋1小费"},
        {049, "试炼屋2小费"},
        {050, "试炼屋3小费"},
        {051, "试炼屋4小费"},
        {052, "女仆小费"},
        {053, "管家小费"},
        {054, "恐怖之家小费"},
        {055, "旅行吟游诗人小费"},
        {056, "训练家宣传片工作室BGM1小费"},
        {057, "训练家宣传片工作室BGM2小费"},
        {058, "宝可美容沙龙馆小费"},
        {059, "不错！收到"},
        {060, "生日祝福"},
        {061, "在线见面的总人数"},
        {062, "擦肩的总人数"},
        {063, "目前的宝可梦里程"},
        {064, "收到的总宝可梦里程"},
        {065, "发送到PGL的总宝可梦里程"},
        {066, "超级特别训练总次数"},
        {067, "超级特别训练总通过次数"},
        {068, "个体值评估次数"},
        {069, "检查垃圾桶次数"},

        {070, "逆属性克制对战次数"},
        {071, "对战屋对战次数"},
        {072, "改变时装次数"},
        {073, "改变发型次数"},
        {074, "收获树果次数"},
        {075, "树果变异次数"},
        {076, "训练家宣传片次数"},
        {077, "朋友狩猎次数"},
        {078, "O-力量使用次数"},

        {079, "秘密基地更新"},
        {080, "获得的秘密基地旗帜"},
        {081, "华丽大赛参赛总计"},
        {082, "GTS交换"},
        {083, "奇迹交换"},
        {084, "偷偷的脚步"},
        {085, "多人华丽大赛"},
        {086, "使用宝可方块"},
        {087, "使用地图导航"},
        {088, "使用图鉴导航"},
        {089, "使用电视导航"},
        {090, "使用游戏导航"},

        {100, "冠军保卫战"},
        {101, "在家里休息"},
        {102, "使用跃起次数"},
        {103, "使用挣扎次数"},
        {104, "无效的瞬间移动次数"},
        {105, "宝可梦晕倒次数"},
        {106, "在对战中攻击盟友次数"},
        {107, "逃跑失败次数"},
        {108, "野生遭遇逃跑次数"},
        {109, "失败的钓鱼次数"},
        {110, "击败宝可梦（最高）"},
        {111, "击败宝可梦（当天）"},
        {112, "捕获宝可梦（最高）"},
        {113, "捕获宝可梦（当天）"},
        {114, "训练者对战（最高）"},
        {115, "训练者对战（当天）"},
        {116, "宝可梦进化（最高）"},
        {117, "宝可梦进化（当天）"},
        {118, "复原化石"},
        {119, "甜甜香气遭遇"},
        {120, "试炼屋测试"},
        {121, "试炼屋等级"},
        {122, "试炼屋分数"},

        {123, "餐厅的最后一次小费: ★☆☆"},
        {124, "餐厅的最后一次小费: ★★☆"},
        {125, "餐厅的最后一次小费: ★★★"},
        {126, "餐厅的最后一次小费: 回转梦想家"},
        {127, "咖啡馆1的最后一次小费"},
        {128, "咖啡馆2的最后一次小费"},
        {129, "咖啡馆2的最后一次小费"},
        {130, "摄影师的最后一次小费"},
        {131, "果汁馆的最后一次小费"},
        {132, "诗人的最后一次小费"},
        {133, "宝可美容沙龙馆修建师的最后一次小费"},
        {134, "试炼屋1的最后一次小费"},
        {135, "试炼屋2的最后一次小费"},
        {136, "试炼屋3的最后一次小费"},
        {137, "试炼屋4的最后一次小费"},
        {138, "女仆的最后一次小费"},
        {139, "管家的最后一次小费"},
        {140, "恐怖之家的最后一次小费"},
        {141, "旅行吟游诗人的最后一次小费"},
        {142, "训练家宣传片工作室BGM1的最后一次小费"},
        {143, "训练家宣传片工作室BGM2的最后一次小费"},
        {144, "宝可美容沙龙馆的最后一次小费"},

        {145, "拍摄的照片"},
        {146, "高空遭遇战(？)"},
        {147, "对战屋连胜: 单打"},
        {148, "对战屋连胜: 双打"},
        {149, "对战屋连胜: 三打"},
        {150, "对战屋连胜: 轮盘"},
        {151, "对战屋连胜: 多人"},
        {152, "ID抽奖获奖"},
        {153, "使用PP回复"},
        {154, "PSS擦肩计数(当天)"},
        {155, "朋友使用"},

        {156, "轮滑鞋次数: 向左旋转"},
        {157, "轮滑鞋次数: 向右旋转"},
        {158, "轮滑鞋次数: 奔跑启动"},
        {159, "轮滑鞋次数: 平行过弯"},
        {160, "轮滑鞋次数: 旋转爆冲"},
        {161, "轮滑鞋次数: 右360°"},
        {162, "轮滑鞋次数: 左360°"},
        {163, "轮滑鞋次数: 旋转"},
        {164, "轮滑鞋次数: 磨"},
        {165, "轮滑鞋次数: 组合"},

        {166, "钓鱼连锁"},
        {167, "在你的基地进行秘密基地对战"},
        {168, "在别人的基地进行秘密基地对战"},
        {169, "华丽大赛精彩照片"},
        {170, "使用飞翔次数"},
        {171, "翱翔高空时间"},
        {172, "使用潜水次数"},
        {173, "使用高空裂缝次数"},
        {174, "被妈妈治愈次数"},
        {175, "离洞绳使用次数"},
        {176, "探宝器使用次数"},
        {177, "训练师再战次数"},
        {178, "兴趣交流 ???"}, // similar to USUM idb

        {179, "遇到异色的宝可梦"},
        {180, "戏法屋通关"},
        {181, "无限船票 1 (擦肩)"},
        {182, "无限船票 2 (神秘礼物)"},
    };

    public static readonly Dictionary<int, string> RecordList_7 = new()
    {
        {000, "Steps Taken"},
        {001, "Times Saved"},
        {002, "Storyline Completed Time"},
        {003, "Total Battles"},
        {004, "Wild Pokémon Battles"},
        {005, "Trainer Battles"},
        {006, "Pokemon Caught"},
        {007, "Pokemon Caught Fishing"},
        {008, "Eggs Hatched"},
        {009, "Pokémon Evolved"},
        {010, "Pokémon Healed at Pokémon Centers"},
        {011, "Link Trades"},
        {012, "Link Battles"},
        {013, "Link Battle Wins"},
        {014, "Link Battle Losses"},
        {015, "Battle Spot Battles"},
        {016, "Battle Spot Wins"},
        {017, "Battle Spot Losses"},
        {018, "Mart Stack Purchases"},
        {019, "Money Spent"},
        {020, "Pokémon deposited at Nursery"},
        {021, "Pokémon Defeated"},
        {022, "Exp. Points Collected (Highest)"},
        {023, "Exp. Points Collected (Today)"},
        {024, "Deposited in the GTS"},
        {025, "Nicknames Given"},
        {026, "Bonus Premier Balls Received"},
        {027, "Battle Points Earned"},
        {028, "Battle Points Spent"},
        {029, "Super Effective Moves Used"},
        {030, "Clothing Count"},
        {031, "Salon Uses"},
        {032, "Berry Harvests"},
        {033, "Trades at the GTS"},
        {034, "Wonder Trades"},
        {035, "Quick Links"},
        {036, "Pokemon Rides"},
        {037, "Beans Given"},
        {038, "Festival Coins Spent"},
        {039, "Poke Beans Collected"},
        {040, "Battle Tree Challenges"},
        {041, "Z-Moves Used"},
        {042, "Balls Used"},
        {043, "Items Thieved"},
        {044, "Moves Used"},
        {045, "Levels Raised"},
        {046, "Ran From Battles"},
        {047, "Rock Smash Items"},
        {048, "Medicine Used"},
        {049, "Pay Day Money Received"},
        {050, "Total Thumbs-Ups"},
        {051, "Times Twirled (Pirouette)"},
        {052, "Record Thumbs-ups"},
        {053, "Pokemon Petted"},
        {054, "Poké Pelago Visits"},
        {055, "Poké Pelago Bean Trades"},
        {056, "Poké Pelago Tapped Pokémon"},
        {057, "Poké Pelago Bean Stacks put in Crate"},
        {058, "Poké Pelago Levels Gained"},
        {059, "Poké Pelago Friendship Increased"},
        {060, "Poké Pelago Eggs Hatched"},
        {061, "Poké Pelago ???"},
        {062, "Battle Video QR Teams Scanned"},
        {063, "Battle Videos Watched"},
        {064, "Battle Videos Rebattled"},
        {065, "RotomDex Interactions"},
        {066, "Guests Interacted With"},
        {067, "Berry Piles (not full) Collected"},
        {068, "Berry Piles (full) Collected"},
        {069, "Items Reeled In"},
        // USUM
        {070, "Roto Lotos"},

        {072, "Stickers Collected"},
        {073, "Mantine Surf BP Earned"},
        {074, "Battle Agency Wins"},

        {100, "Champion Title Defense"},
        {101, "Times rested at home"},
        {102, "Times Splash used"},
        {103, "Times Struggle used"},
        {104, "Moves used with No Effect"},
        {105, "Own Fainted Pokémon"},
        {106, "Times attacked ally in battle"},
        {107, "Failed Run Attempts"},
        {108, "Wild encounters that fled"},
        {109, "Failed Fishing Attempts"},
        {110, "Pokemon Defeated (Highest)"},
        {111, "Pokemon Defeated (Today)"},
        {112, "Pokemon Caught (Highest)"},
        {113, "Pokemon Caught (Today)"},
        {114, "Trainers Battled (Highest)"},
        {115, "Trainers Battled (Today)"},
        {116, "Pokemon Evolved (Highest)"},
        {117, "Pokemon Evolved (Today)"},
        {118, "Fossils Restored"},
        {119, "Photos Rated"},
        {120, "Best (Super) Singles Streak"},
        {121, "Best (Super) Doubles Streak"},
        {122, "Best (Super) Multi Streak"},
        {123, "Loto-ID Wins"},
        {124, "PP Raised"},
        {125, "Amie Used"},
        {126, "Fishing Chains"},
        {127, "Shiny Pokemon Encountered"},
        {128, "Missions Participated In"},
        {129, "Facilities Hosted"},
        {130, "QR Code Scans"},
        {131, "Moves learned with TMs"},
        {132, "Café Drinks Bought"},
        {133, "Trainer Card Photos Taken"},
        {134, "Evolutions Cancelled"},
        {135, "SOS Battle Allies Called"},
        {136, "Friendship Raised"},
        {137, "Battle Royal Dome Battles"},
        {138, "Items Picked Up after Battle"},
        {139, "Ate in Malasadas Shop"},
        {140, "Hyper Trainings Received"},
        {141, "Dishes eaten in Battle Buffet"},
        {142, "Pokémon Refresh Accessed"},
        {143, "Pokémon Storage System Log-outs"},
        {144, "Lomi Lomi Massages"},
        {145, "Times laid down in Ilima's Bed"},
        {146, "Times laid down in Guzma's Bed"},
        {147, "Times laid down in Kiawe's Bed"},
        {148, "Times laid down in Lana's Bed"},
        {149, "Times laid down in Mallow's Bed"},
        {150, "Times laid down in Olivia's Bed"},
        {151, "Times laid down in Hapu's Bed"},
        {152, "Times laid down in Lusamine's Bed"},
        {153, "Ambush/Smash post-battle items received"},
        {154, "Rustling Tree Encounters"},
        {155, "Ledges Jumped Down"},
        {156, "Water Splash Encounters"},
        {157, "Sand Cloud Encounters"},
        {158, "Outfit Changes"},
        {159, "Battle Royal Dome Wins"},
        {160, "Pelago Treasure Hunts"},
        {161, "Pelago Training Sessions"},
        {162, "Pelago Hot Spring Sessions"},
        {163, "Special QR 1"},
        {164, "Special QR 2"},
        {165, "Special QR Code Scans"},
        {166, "Island Scans"},
        {167, "Rustling Bush Encounters"},
        {168, "Fly Shadow Encounters"},
        {169, "Rustling Grass Encounters"},
        {170, "Dirt Cloud Encounters"},
        {171, "Wimpod Chases"},
        {172, "Berry Tree Battles won"},
        {173, "Bubbling Spot Encounters/Items"},
        {174, "Times laid down in Own Bed"},
        // global missions
        {175, "Catch a lot of Pokémon!"},
        {176, "Trade Pokémon at the GTS!"},
        {177, "Hatch a lot of Eggs!"},
        {178, "Harvest Poké Beans!"},
        {179, "Get high scores with your Poké Finder!"},
        {180, "Find Pokémon using Island Scan!"},
        {181, "Catch Crabrawler!"},
        {182, "Defend your Champion title!"},
        {183, "Fish Pokémon at rare spots!"},
        {184, "Battle Royal!"},
        {185, "Try your luck!"},
        {186, "Get BP at the Battle Tree!"},
        {187, "Catch a lot of Pokémon!"},

        // USUM
        {188, "Ultra Wormhole Travels"},
        {189, "Mantine Surf Plays"},
        {190, "Photo Club Photos saved"},
        {191, "Battle Agency Battles"},
        // 192-194 unknown
        {195, "Photo Club Sticker usage"},
        {196, "Photo Club Photo Shoots"},
        {197, "Highest Wormhole Travel Distance"},
        {198, "Highest Mantine Surf BP Earned"},
    };

    public static readonly Dictionary<int, string> RecordList_8 = new()
    {
        {00, "egg_hatching"},
        {01, "capture_wild"},
        {02, "capture_symbol"},
        {03, "capture_raid"},
        {04, "capture_camp"},
        {05, "capture_fishing"},
        {06, "total_capture"},
        {07, "dress_up"},
        {08, "training"},
        {09, "personal_change"},
        {10, "rotomu_circuit"},
        {11, "npc_trade"},
        {12, "pretty"},
        {13, "chain_encount"},
        {14, "hall_of_fame"},
        {15, "fossil_restore"},
        {16, "wild_pokemon_encount"},
        {17, "trade"},
        {18, "magical_trade"},
        {19, "one_day_captured"},
        {20, "one_day_evolution"},
        {21, "total_walk"},
        {22, "total_watt"},
        {23, "total_all_battle"},
        {24, "campin"},
        {25, "battle_point"},
        {26, "win_battle_point"},
        {27, "license_trade"},
        {28, "use_skill_record"},
        {29, "use_exp_ball"},
        {30, "use_personal_change_item"},
        {31, "clothes"},
        {32, "evolution"},
        {33, "net_battle"},
        {34, "cooking"},
        {35, "poke_job_return"},
        {36, "get_rare_item"},
        {37, "whistle"},
        {38, "bike_dash"},
        {39, "tree_shake"},
        {40, "tree_nut"},
        {41, "battle_lose"},
        {42, "recipe"},
        {43, "raid_battle"},
        {44, "total_money"},
        {45, "create_license_card"},
        {46, "change_hair"},
        /* 47 */ {G8BattleTowerSingleWin, "battle_tower_single_win"},
        /* 48 */ {G8BattleTowerDoubleWin, "battle_tower_double_win"},
        {49, "now_money"},

        // The Records Block only stores 50 entries.
        // Record IDs for future expansion content is instead handled separately.

        // DLC
        {50, "cormorant_robo"}, // saved in B9C0ECFC 
        {51, "battle_rom_mark"}, // saved in BB1DE8EF
    };

    public const int G8BattleTowerSingleWin = 47;
    public const int G8BattleTowerDoubleWin = 48;
}
